school/urls.py
from django.contrib import admin
from django.urls import path,include

# Media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('voting.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('students/', include('members.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

voting/urls.py
from django.urls import path

from .views import *

app_name = "vote"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("success/", SuccessView.as_view(), name="success"),
    path("already_voted/", AlreadyVoted.as_view(), name="already"),
    path("voting/<int:pk>", VoteCandidateView, name="voting"),
]

voting/models.py
from django.db import models

from django.contrib.auth import get_user_model


# Create your models here.

def get_image_extension(filename):
    if "." in filename:
        return filename.split(".")[-1]
    else:
        return None

def get_candidate_image_filepath(self, filename):
    """
    Returns the candidate image filepath
    """
    extension = get_image_extension(filename)

    if extension is not None:
        return f"images/candidates/{self.id}/image.{extension}"
    else:
        return f"images/candidates/{self.id}/image.png"

def get_default_candidate_image():
    """
    Returns the default profile image
    """

    return "images/default/default_gilflc.png"


class Candidate(models.Model):

    PRIMARY = 1
    HIGH = 2

    level_choices = (
        (PRIMARY, 'Primaria'),
        (HIGH, 'Bachillerato'),
    )

    level = models.PositiveSmallIntegerField(
        choices=level_choices,
        default=PRIMARY,
    )

    candidates_name = models.CharField(max_length=170)

    proposal = models.TextField()

    image = models.ImageField(max_length=255, upload_to=get_candidate_image_filepath,
                              default=get_default_candidate_image, blank=True, null=True)

    votes = models.ManyToManyField(
        get_user_model(), related_name="candidate_name", blank=True
    )


    @property
    def number_of_votes(self):
        """
        Returns the votes of a candidate
        """
        return self.votes.count()

    def __str__(self):
        return self.candidates_name

voting/views.py
from django.shortcuts import render

from django.views.generic import TemplateView, DetailView, View

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.views.generic import ListView

from django.http import HttpResponseRedirect

from django.urls import reverse_lazy, reverse

from .models import *

# Create your views here.


# class Userhasntvoted(UserPassesTestMixin):
#     def test_func(self):
#         return not self.request.user.has_voted 
    
    # def handle_no_permission(self):
    #     '''
    #     If the user has voted, redirect  to the already_voted view
    #     '''
    #     if self.raise_exception:
    #         raise PermissionDenied(self.get_permission_denied_message())
    #     return HttpResponseRedirect(reverse_lazy('vote:already'))

class CustomLoginRequiredMixin(LoginRequiredMixin):
    login_url = 'members:signup'


class HomeView(CustomLoginRequiredMixin,  ListView):
    
    model = Candidate

    # queryset = Candidate.objects.filter(level=self.request.user.level)

    template_name = "voting/home.html"
    context_object_name = "candidates"

    def get_queryset(self):
        qs =  super().get_queryset()
        return qs.filter(level=self.request.user.grade.level)
    

class AlreadyVoted(TemplateView):
    template_name = "voting/already_voted.html"


# class CandidateDetailView(LoginRequiredMixin, DetailView):
#     model = Candidate
#     template_name = "voting/details.html"
#     login_url = 'members:signup'
#     context_object_name = "candidate"


class SuccessView(TemplateView):
    template_name = "voting/success.html"


def VoteCandidateView(request, pk):
    candidate = Candidate.objects.get(id=pk)

    if candidate.votes.filter(id=request.user.id).exists():
        """
        If the user has already voted, redirect to the success
        """
        return HttpResponseRedirect(reverse('vote:success'))
    else:
        candidate.votes.add(request.user)
        user = request.user
        user.has_voted = True
        user.save()
        return HttpResponseRedirect(reverse('vote:success'))
    return HttpResponseRedirect(reverse('vote:home'))

    # if post.upvotes.filter(id=request.user.id).exists():
    #     post.upvotes.remove(request.user)
    # else:
    #     post.upvotes.add(request.user)
    # return HttpResponseRedirect(reverse('blog:article_page', args=[str(pk)]))

voting/templates/voting/already_voted.html
U have already voted ://///

voting/templates/voting/details.html
Details page :))

{% if candidate.image %}
<a href="{% url 'vote:detail' candidate.pk %}"></a><img src="{{candidate.image.url}}" alt="Candidate image">
{% endif %}
<br>
{{candidate.candidates_name}}
<br>
{{candidate.proposal}}


<div class="vote">
    <form action="{% url 'vote:voting' candidate.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" name="post_upvote" value="{{ candidate.pk }}" class="btn btn-danger btn-sm mt-4">Votame
        </button>
    </form>
</div>

voting/templates/voting/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Vota{% endblock title %}


{% block super_body_content %}

<div class="vote-wrapper">
    {% if not user.has_voted %}
    <div class="mx-auto text-center py-4">
        <h1 class="fw-bold">Votaciones {% if user.grade.level == 1 %}Primaria {% else %}Bachillerato{% endif %}</h1>
    </div>
    <div class="container pt-4">
        <div class="row g-md-5 g-3">
            {% for candidate in candidates %}
            <div class="col-12 col-md-6">
                <div class="card mb-3">
                    {% if candidate.image %}
                    <img src="{{ candidate.image.url }}" class="card-img-top" alt="Candidate image">
                    {% endif %}
                    <div class="card-body">
                        <div class="py-2">
                            <h3 class="card-title fw-bold">{{ candidate.candidates_name }}</h3>
                        </div>
                        <p class="card-text">{{candidate.proposal}}</p>
                    </div>

                    <div class="vote py-3 px-md-4 d-flex justify-content-center">
                        <form action="{% url 'vote:voting' candidate.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" name="post_upvote" value="{{ candidate.pk }}"
                                class="btn btn-primary  mt-4">Votar a {{candidate.candidates_name}}
                            </button>
                        </form>
                    </div>
                </div>

            </div>

            {% endfor %}
        </div>
    </div>

    {% else %}

    <div class="container">

        <div class="d-flex justify-content-center">
            <div class="my-5">
                <h1 class="fw-bold">
                    Lo siento, Ya has votado a tu candidato
                </h1>
            </div>
        </div>
        <div class="py-3 d-flex justify-content-center">
            <img src="{% static 'images/already.svg' %}" alt="Already voted" class="img-fluid already-img">
        </div>
    </div>

    {% endif %}
</div>

{% endblock super_body_content %}

voting/templates/voting/success.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Ya has votado{% endblock title %}


{% block super_body_content %}

<div class="vote-wrapper">

    <div class="container">

        <div class="d-flex justify-content-center">
            <div class="my-5">
                <h1 class="fw-bold">
                    Listo! Ya has votado a tu candidato
                </h1>
                <p class="d-flex justify-content-center">
                    Ya puedes cerrar esta página
                </p>
            </div>
        </div>
        <div class="py-3 d-flex justify-content-center">
            <img src="{% static 'images/voted.svg' %}" alt="Already voted" class="img-fluid already-img">
        </div>
    </div>

</div>
{% endblock super_body_content %}