dashboard/urls.py
from django.urls import path

from .views import *

app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("elementary/", DashboardElementaryView.as_view(), name="elementary"),
    path("high_school/", DashboardHighSchoolView.as_view(), name="high"),
    path("notallowed/", DashboardNotAllowedView.as_view(), name="not"),
]

school/urls.py
from django.contrib import admin
from django.urls import path,include

# Media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('voting.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('students/', include('members.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.

from django.views.generic import TemplateView

from django.contrib.auth.mixins import UserPassesTestMixin

from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse

from voting.views import CustomLoginRequiredMixin

# Candidate model

from voting.models import Candidate


# path("", DashboardHomeView.as_view(), name="home"),
# path("elementary/", DashboardElementaryView.as_view(), name="elementary"),
# path("high_school/", DashboardHighSchoolView.as_view(), name="high"),
# path("notallowed/", DashboardNotAllowedView.as_view(), name="high"),

class IsStaff(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_staff 
    
    def handle_no_permission(self):
        '''
        If the user has voted, redirect  to the already_voted view
        '''
        if self.raise_exception:
            raise PermissionDenied(self.get_permission_denied_message())
        return HttpResponseRedirect(reverse_lazy('dashboard:not'))
    

class DashboardPermission(CustomLoginRequiredMixin, IsStaff):
    """
    Manage if the user is authenticated, if not it redirects him to the sign up page:
    Then if the user is authenticated, but if he isn't staff shows an error page
    """


class DashboardHomeView(DashboardPermission, TemplateView):
    """
    Home page that allows to choose between high school and elementary
    """
    template_name = "dashboard/home.html"


    
class DashboardNotAllowedView(TemplateView):
    """
    Custom Permision Denied Page
    """
    template_name = "dashboard/not_allowed.html"


class DashboardElementaryView(DashboardPermission, TemplateView):
    template_name = "dashboard/elementary.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["candidates"] = Candidate.objects.filter(level=1)
        return context
    

class DashboardHighSchoolView(DashboardPermission, TemplateView):
    template_name = "dashboard/high.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["candidates"] = Candidate.objects.filter(level=2)
        return context
    

dashboard/templates/dashboard/elementary.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Primaria{% endblock title %}

{% block body_content %}

<div class="d-flex justify-content-center">
    <div class="text-center">
        <div class="py-5">
            <h1 class="fw-bold">
                Resultados Primaria
            </h1>
            <p class="text-muted">Estos resultados son los resultados de la votación para personero en Primaria</p>
        </div>
    </div>
</div>

{% include "dashboard/table.html" %}

{% endblock body_content %}

dashboard/templates/dashboard/high.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Bachillerato{% endblock title %}

{% block body_content %}
<div class="d-flex justify-content-center text-center">
    <div class="py-5">
        <h1 class="fw-bold">Resultados Bachillerato</h1>
        <p class="text-muted">Estos resultados son los resultados de la votación para personero en Bachillerato</p>
    </div>
</div>

{% include "dashboard/table.html" %}

{% endblock body_content %}

dashboard/templates/dashboard/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block super_body_content %}


<div class="container">
    <div class="py-4">
        <div class="mx-auto text-center">
            <h1 class="fw-bold">Hola este es el dashboard para docentes y administrativos!</h1>
            <p class="text-muted">Si deseas puedes ver las votaciones de Primaria y Bachillerato</p>

        </div>
    </div>

    <div class="p-4">
        <div class="d-flex justify-content-center">
            <a href="{% url 'dashboard:elementary' %}" class="btn btn-primary w-100">Personeritos 1° - 5°</a>
        </div>
    </div>
    <div class="p-4">
        <div class="d-flex justify-content-center">
            <a href="{% url 'dashboard:high' %}" class="btn btn-success w-100">Personeros 6° - 11°</a>
        </div>
    </div>
</div>
{% endblock super_body_content %}

dashboard/templates/dashboard/not_allowed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}No permitido{% endblock title %}

{% block body_content %}

<div class="d-flex justify-content-center">
    <div class="py-5">
        <h1 class="fw-bold">
            Lo siento no esta permitido que estes aqui
        </h1>
    </div>
</div>
<div class="d-flex justify-content-center">
    <div class="py-5 text-align-center mx-auto">
        <p>Si eres administrativo y deseas acceder a los resultados de la votacion puedes hacerlo teniendo una cuenta
            administrativa, comunicate con Daniel Diaz del grado 11.</p>
    </div>
</div>


{% endblock body_content %}

dashboard/templates/dashboard/table.html
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead class="table-dark">
            <th scope="col">Nombre del candidato</th>
            <th scope="col">Número de votos</th>
        </thead>
        <tbody>
            {% for candidate in candidates %}
            <tr>
                <td><span class="fw-bold">{{candidate.candidates_name}}</span></td>
                <td><span>{{candidate.number_of_votes}}</span></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>