dashboard/urls.py
from django.urls import path

from .views import *

app_name = "dashboard"

urlpatterns = [
    path("", DashboardHomeView.as_view(), name="home"),
    path("elementary/", DashboardElementaryView.as_view(), name="elementary"),
    path("high_school/", DashboardHighSchoolView.as_view(), name="high"),
    path("notallowed/", DashboardNotAllowedView.as_view(), name="not"),
]

school/urls.py
from django.contrib import admin
from django.urls import path,include

# Media
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('voting.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('students/', include('members.urls')),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="{% block description %}
        {% endblock description %}">

        {% comment "" %}This meta tag show an image when the site is shared.{% endcomment %}



        <title>{% block title %}{% endblock title %} | Votaciones Personero</title>
        {% comment %} Favicons {% endcomment %}

        {% comment %} <link rel="icon" href="{% static 'images/favicon.png' %}"> {% endcomment %}
        <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}"/>

        {% comment %} google fonts: Montserrat {% endcomment %}
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        {% block google_fonts %}
        <link href="https://fonts.googleapis.com/css2?family=Cedarville+Cursive&family=Poppins:ital@1&display=swap"
            rel="stylesheet">
        {% endblock google_fonts %}


        {% block fontawesome %}
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
            integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
        {% endblock fontawesome %}

        {% comment %} Bootstrap CSS {% endcomment %}
        {% block bootstrap %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        {% endblock bootstrap %}

        {% block head_links %}
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        {% comment %} Custom css {% endcomment %}
        {% comment %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}"> {% endcomment %}

        {% endblock head_links %}

    </head>

    <body>
        {% include "navbar.html" %}
        {% block super_body_content %}
        <div class="container">
            {% block body_content %}
            {% endblock body_content %}
        </div>

        {% endblock super_body_content %}
        {% comment %} JavaScript Bundle with Popper {% endcomment %}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
        </script>


    </body>

</html>

templates/navbar.html
<!-- As a heading -->
<nav class="navbar navbar-light bg-light my-navbar" style="">
    <div class="container-fluid">
        <div class="d-flex justify-content-start">
            <span class="navbar-brand mb-0 text-muted align-self-start"
                style="font-family: 'Poppins', sans-serif; font-size: 0.9rem;">Creado por
                Daniel Diaz 11°</span>
        </div>
        <div class="d-flex justify-content-end">
            {% if user.is_staff or user.is_admin %}
            <span> <a href="{% url 'dashboard:home' %}" class="navbar-brand mb-0 text-muted align-self-start"
                    style="font-family: 'Poppins', sans-serif; font-size: 0.9rem;"> Votaciones -
                    Resultados</a></span>
            {% else %}

            <span class="navbar-brand mb-0 text-muted align-self-start"
                style="font-family: 'Poppins', sans-serif; font-size: 0.9rem;">Votaciones Liceo carmelita <i
                    class="fas fa-graduation-cap px-2"></i></span>

            {% endif %}
        </div>
    </div>
    </div>
</nav>